// Dev / E2E harness entry — NOT part of the published bundle.
//
// `index.html` loads this module so `npm run dev` and the Playwright
// harness can mount() Solar against a mock LSDP server. Reads URL query
// params (orion / token / mode / scene / session), falls back to sane
// defaults, and mounts. The production counterpart is generated by
// scripts/build-host-html.mjs (inlined into dist/index.html).
//
// Excluded from tsconfig.lib.json + the dts build + the Vite library
// entry — it never ships in solar.js.

import { mount } from "./mount";
import type { SolarMode } from "./types";

const params = new URLSearchParams(window.location.search);
const orionUrl =
  params.get("orion") ?? `ws://${location.host}/lsdp/v1/show/stream`;
const token = params.get("token") ?? "";
const modeParam = params.get("mode") ?? "broadcast";
const mode: SolarMode = (
  ["broadcast", "control", "test"] as const
).includes(modeParam as SolarMode)
  ? (modeParam as SolarMode)
  : "broadcast";
const scene = params.get("scene") ?? undefined;
const testSession = params.get("session") ?? undefined;

const target = document.getElementById("scene");
if (!(target instanceof HTMLElement)) {
  throw new Error("dev-entry : #scene target missing");
}

mount({
  target,
  orionUrl,
  token,
  mode,
  ...(mode === "test" && scene ? { scene } : {}),
  ...(mode === "test" && testSession ? { testSession } : {}),
  onError: (err) => {
    // Dev only — surface to the console. Broadcast hosts must not render
    // chrome ; the operator overlay (control/test modes) is the runtime's
    // own concern now. Log the SolarError fields explicitly (it is a plain
    // object, not an Error) so `code`/`message` never collapse to
    // `[object Object]` in a string-coercing console bridge.
    console.error(
      `[solar dev] ${err.code}: ${err.message}` +
        (err.recoverable ? " (recoverable)" : " (fatal)"),
    );
  },
});
